name: Functional Testing

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  pytest:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false
      - name: Install the project
        run: uv sync --extra test
      - name: Run tests with coverage
        run: uv run pytest --cov=src --cov-report=xml --cov-report=html
      - name: Run coverage for examples
        run: uv run pytest --cov=examples --cov-report=xml --cov-report=html
      - name: Upload coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: |
            coverage.xml
            htmlcov/
